dist: xenial
sudo: false
language: node_js
node_js:
  - 12
install:
  - npm install
script:
  - npm run-script build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  on:
    branch: master